title: Katrin Maliatski
description: "A simple, whitespace theme for academics."

remote_theme: pages-themes/minimal@v0.2.0
plugins:
  - jekyll-remote-theme
  - jekyll-feed

url: "https://kmaliatski.github.io"
baseurl: "/katrinmaliatski.github.io"

lang: en
theme: minimal

# Optional settings
author:
  name: Katrin Maliatski

# GitHub Pages specific settings
github:
  is_project_page: true
