source "https://rubygems.org"

gem "jekyll", "~> 4.3.4"
gem "jekyll-feed"
gem "jekyll-sitemap"
gem "jekyll-seo-tag"
gem "jekyll-scholar"
gem "jekyll-include-cache"
gem "jekyll-remote-theme"
gem "jekyll-archives"
gem "jekyll-email-protect"
gem "jekyll-get-json"
gem "jekyll-imagemagick"
gem "jekyll-jupyter-notebook"
gem "jekyll-paginate"
gem "jekyll-redirect-from"
gem "jekyll-optional-front-matter"
gem "jekyll-readme-index"
gem "jekyll-default-layout"
gem "jekyll-titles-from-headings"
gem "jemoji"
gem "webrick", "~> 1.7" # required to serve locally in Ruby 3+
