source "https://rubygems.org"

gem "jekyll", "~> 4.3.4"
gem "jekyll-feed"
gem "jekyll-sitemap"
gem "jekyll-seo-tag"
gem "jekyll-scholar"
gem "jekyll-include-cache"
gem "jekyll-remote-theme"
gem "jekyll-archives"
gem "jekyll-email-protect"
gem "jekyll-get-json"
gem "jekyll-imagemagick"
